program Bhagavad_Gita;
uses crt;
var a:integer;

Procedure Cover;
begin
  writeln('Bhagavad-gita');
  writeln('(Nyanyian Tuhan)');
  writeln;
  writeln;
  writeln('(Darmayasa)');
  writeln('Yayasan Dharma Sthapanam');
  writeln;
  writeln;
  writeln('Program by Vkurpmax9');
end;

Procedure bab;
begin
  writeln('Adhyaya 1 - Arjuna Visada Yoga');
  writeln('Adhyaya 2 - Sankhya Yoga');
  writeln('Adhyaya 3 - Karma Yoga');
  writeln('Adhyaya 4 - Jnana Yoga');
  writeln('Adhyaya 5 - Samnyasa Yoga');
  writeln('Adhyaya 6 - Dhyana Yoga');
  writeln('Adhyaya 7 - Jnana Vijnana Yoga');
  writeln('Adhyaya 8 - Aksarabrahma Yoga');
  writeln('Adhyaya 9 - Raja Vidya Raja Guyha Yoga');
  writeln('Adhyaya 10 - Vibhuti Yoga');
  writeln('Adhyaya 11 - Visvarupa Darsana Yoga');
  writeln('Adhyaya 12 - Bhakti Yoga');
  writeln('Adhyaya 13 - Ksetra-Ksetrajna Vibhaga Yoga');
  writeln('Adhyaya 14 - Gunatraya Vibhaga Yoga');
  writeln('Adhyaya 15 - Purusottama Yoga');
  writeln('Adhyaya 16 - Daiva-Asura-Sampad Vibhaga Yoga');
  writeln('Adhyaya 17 - Sraddha Traya Vibhaga Yoga');
  writeln('Adhyaya 18 - Moksa Samnyasa Yoga');
end;

Procedure A1;
var s:integer;

begin
  repeat
    clrscr;
    writeln('Pilih Sloka (1 - 47)');
    readln(s);
    case s of
    0: halt;
    1: begin
         writeln('Dhrtarastra uvaca');
         writeln('dharma ksetre kuru ksetre');
         writeln('sama veta yuyutsavah');
         writeln('mamakah pandavas caiva');
         writeln('kim akurvata sanjaya');
         writeln;
         writeln('Maharaja Dhrtarastra berkat: Wahai Sanjaya,');
         writeln('putra-putraku dan putra-putra Pandu sedang');
         writeln('berkumpul di medan suci Kuruksetra dengan');
         writeln('tekad untuk bertemput, (ceritakanlah padaku)');
         writeln('apa yang mereka (sedang) lakukan?');
       end;
    2: begin
         writeln('sanjaya uvaca');
         writeln('drstva tu pandavanikam');
         writeln('vyudham duryodhanas tada');
         writeln('acaryam upasangamya');
         writeln('raja vacanam abravit');
         writeln;
         writeln('Sanjaya berkata: Wahai Maharaja Dhrtarastra,');
         writeln('setelah melihat tentara Pandava yang disusun');
         writeln('rapi dalam barisan militer posisi Vajra-vyuha,');
         writeln('Raja Duryodhana mendekati Acharya Drona dan');
         writeln('berkata sebagai berikut:');
       end;
    3: begin
         writeln('pasyaitam pandu-putranam');
         writeln('acarya mahatim camum');
         writeln('vyudham drupada-putrena');
         writeln('tava sisyena dhimata');
         writeln;
         writeln('Wahai Guru..., lihatlah pasukan kuat putra-putra');
         writeln('Pandu, ditata rapi oleh siswa anda yang cerdas,');
         writeln('putra Maharaja Drupada.');
      end;
    4: begin
         writeln('atra sura mahesv-asa');
         writeln('bhimarjuna-sama yudhi');
         writeln('yuyudhano viratas ca');
         writeln('drupadas ca maharathah');
         writeln;
         writeln('Di dalam medan perang ini terdapat para Ksatria');
         writeln('pemanah hebat yang memiliki kemampuan');
         writeln('berperang setingkat Bhima dan Arjuna.');
         writeln('Ksatria-ksatria hebat tersebut antara lain');
         writeln('Yuyudhana, Virata dan Drupada.');
       end;
    5: begin
         writeln('dhrstaketus cekitanah');
         writeln('kasirajas ca viryavan');
         writeln('purujit kuntibhojas ca');
         writeln('saibyas ca nara-pungavah');
         writeln;
         writeln('Terdapat pula ksatria-ksatria hebat seperti');
         writeln('Dhrstaketu, Cekitana, Kasiraja dan juga Purujit,');
         writeln('Kuntibhoja serta Saibya yang terkenal memiliki');
         writeln('kepahlawanan tinggi.');
       end;
    6: begin
         writeln('yudhamanyus ca vikranta');
         writeln('uttamaujas ca viryavan');
         writeln('saubhadro draupadeyas ca');
         writeln('sarva eva maharathah');
         writeln;
         writeln('Hadir pula ksatria-ksatria hebat seperti');
         writeln('Yudhamanyu sang penakluk musuh, Uttamauja');
         writeln('yang pemberani dan juga putra Subadra serta');
         writeln('putra-putra Draupadi. Mereka semua adalah');
         writeln('ksatria sangat hebat dalam pertempuran');
       end;
    7: begin
         writeln('asmakam tu visista ye');
         writeln('tan nibodha dvijottama');
         writeln('nayaka mama sainyasya');
         writeln('sanjnartham tan bravimi te');
         writeln;
         writeln('Guruku Sang Dwija Utama, ketahuilah');
         writeln('tokoh-tokoh hebat yang berada di pihak kita.');
         writeln('Sebagai informasi untuk Anda, izinkanlah');
         writeln('hamba menyampaikan keterangan tentang');
         writeln('komandan-komanda yang memimpin pasukan');
         writeln('hamba.');
       end;
    8: begin
         writeln('bhavan bhismas ca karnas ca');
         writeln('krpas ca samitinjaya');
         writeln('asvatthama vikarnas ca');
         writeln('saumadattis tathaiva ca');
         writeln;
         writeln('Tokoh-tokoh yang selalu menang dalam');
         writeln('peperangan seperti Guru sendiri (Acarya Drona),');
         writeln('kakek Bhisma, Karna dan juga Acarya Krpa,');
         writeln('Asvatthama, Vikarna serta Raja Bhurisrava, putra');
         writeln('Somadatta');
       end;
    9: begin
         writeln('anye ca bahavah sura');
         writeln('mad-arthe tyakta-jivitah');
         writeln('nana-sastra-praharana');
         writeln('sarve yuddha-visaradah');
         writeln;
         writeln('Dan juga banyak ksatria hebat lainnya');
         writeln('yang bersedia mengorbankan nyawanya');
         writeln('demi kepentingan hamba. Mereka mahir');
         writeln('menggunakan berbagai jenis senjata serta');
         writeln('semua sangat hebat di dalam pertempuran.');
        end;
    10: begin
          writeln('aparyaptam tad asmakam');
          writeln('balam bhismabhiraksitam');
          writeln('paryaptam tv idam etesam');
          writeln('balam bhimabhiraksitam');
          writeln;
          writeln('Kekuatan pasukan kita yang dilindungi oleh');
          writeln('kakek Bhisma tidak dapat diuku. Sedangkan');
          writeln('pasukan mereka yang dilindungi oleh Bhima');
          writeln('mempunyai kekuatan sangat terbatas.');
        end;
    11: begin
          writeln('ayanesu ca sarvesu');
          writeln('yatha-bhagam avasthitah');
          writeln('bhismam evabhiraksantu');
          writeln('bhavantah sarva eva hi');
          writeln;
          writeln('Oleh karena itu, anda semua hendaknya bersiaga');
          writeln('pada posisi strategis di dalam barisan pasukan');
          writeln('masing-masing dan menjaga Kakek Bhisma dari');
          writeln('segala arah');
        end;
    12: begin
          writeln('tasya sanjanayan harsam');
          writeln('kuru-vrddhah pitamahah');
          writeln('simha-nadam vinadyoccaih');
          writeln('sankham dadhmau pratapavan');
          writeln;
          writeln('Kegembiraan Duryodhana bertambah besar');
          writeln('ketika kakek tertua dinasti Kuru yang gagah');
          writeln('perkasa meniup sangkhakalanya dengan keras');
          writeln('bagaikan suara singa mengaum.');
        end;
    13: begin
          writeln('tatah sankhas ca bheryas ca');
          writeln('panavanaka-gomukhah');
          writeln('sahasaivabhyahanyanta');
          writeln('sa sabdas tumulo''bhavat');
          writeln;
          writeln('Sesudah itu, tiba-tiba semua sangkhakala,');
          writeln('gendang, bedug dan terompet dibunyikan');
          writeln('sekaligus, sehingga suaranya menjadi sangat');
          writeln('menggemparkan.');
        end;
    14: begin
          writeln('tatah svetair hayair yukte');
          writeln('mahati syandane sthitau');
          writeln('madhavah pandavas caiva');
          writeln('divyau sankhau pradadhmatuh');
          writeln;
          writeln('Di pihak lain, berdiri di atas kereta gagah yang');
          writeln('ditarik oleh kuda-kuda berwarna putih, Krsna dan');
          writeln('Arjuna juga membunyikan sangkhakala saktinya.');
        end;
    15: begin
          writeln('pancajanyam hrsikeso');
          writeln('devadattam dhananjayah');
          writeln('paundram dadhmau maha-sankham');
          writeln('bhima-karma vrkodarah');
          writeln;
          writeln('Sri Krsna meniup sangkhakala bernama');
          writeln('Pancajanya, Arjuna meniup sangkhakala');
          writeln('bernama Devadatta, Bhima yang sangat kuat');
          writeln('melakukan pekerjaan berat-berat, meniup');
          writeln('sangkhakala hebatnya bernama Paundra.');
        end;
    16: begin
          writeln('anantavijayam raja');
          writeln('kunti-putro yudhisthirah');
          writeln('nakulah sahadevas ca');
          writeln('sughosa-manipuspakau');
          writeln;
          writeln('Putra Kunti, Raja Yudhisthira meniup');
          writeln('sangkhakalanya bernama Anantavijaya,');
          writeln('sedangkan Nakula dan Sahadewa');
          writeln('masing-masing meniup sangkhakalanya');
          writeln('bernama Sughosa dan Manipuspaka.');
        end;
    17: begin
          writeln('kasyas ca paramesva-asah');
          writeln('sikhandi ca maha-rathah');
          writeln('dhrstadyumno viratas ca');
          writeln('satyakis caparajitah');
          writeln;
          writeln('Raja Kasi, pemanah yang sagnat hebat, Sikhandi,');
          writeln('ksatria agung, juga para ksatria yang tak');
          writeln('terkalahkan seperti Dhrstadyumna, Virata dan');
          writeln('Satyaki');
        end;
    18: begin
          writeln('drupado draupadeyas ca');
          writeln('sarvasa prthivi-pate');
          writeln('saubhadras ca maha-bahuh');
          writeln('sankhan dadhmuh prthak prthak');
          writeln;
          writeln('Drupada, putra-putra Draupadi dan lain-lain, wa-');
          writeln('hai Tuanku Raja Penguasa Bumi, juga putra-putra');
          writeln('Subhadra yang sangat perkasa, mereka semua');
          writeln('meniup sangkhakalanya masing-masing.');
        end;
    19: begin
          writeln('sa ghoso dhartarastranam');
          writeln('hrdayani vyadarayat');
          writeln('nabhas ca prthivim caiva');
          writeln('tumulo''bhyanunadayan');
          writeln;
          writeln('Gemuruh bunyi sangkhakala-sangkhakala itu');
          writeln('menggema mengerika diatas bumi maupun');
          writeln('langit, membuat nyali para Putra Dhrtarastra');
          writeln('menjadi ciut');
        end;
    20: begin
          writeln('Atha vyavasthitan drstva');
          writeln('dhartarastran kapi-dhvajah');
          writeln('pravrtte sastra-sampate');
          writeln('dhanur udyamya pandava');
          writeln;
          writeln('hrsikesam tada vakyam');
          writeln('idam aha mahipate');
          writeln;
          writeln('Wahai Maharaja Dhrtarastra..., setelah Arjuna');
          writeln('yang bendera keretanya bergambar Hanuman');
          writeln('mengamati posisi para putra Dhrtarastra, maka');
          writeln('ia mengangkat busur, siap untuk melepaskan');
          writeln('anak panahnya dan berkata sebagai berikut');
          writeln('kepada Sri Krsna:');
        end;
    21: begin
          writeln('Atha vyavasthitan drstva');
          writeln('dhartarastran kapi-dhvajah');
          writeln('pravrtte sastra-sampate');
          writeln('dhanur udyamya pandava');
          writeln;
          writeln('hrsikesam tada vakyam');
          writeln('idam aha mahipate');
          writeln;
          writeln('Wahai Maharaja Dhrtarastra..., setelah Arjuna');
          writeln('yang bendera keretanya bergambar Hanuman');
          writeln('mengamati posisi para putra Dhrtarastra, maka');
          writeln('ia mengangkat busur, siap untuk melepaskan');
          writeln('anak panahnya dan berkata sebagai berikut');
          writeln('kepada Sri Krsna:');
          readln;
          writeln('arjuna uvaca');
          writeln('senayor ubhayor madhye');
          writeln('ratham sthapaya me''cyuta');
          writeln;
          writeln('yavad etan nirikse''ham');
          writeln('yoddhu-kaman avasthitan');
          writeln('kair maya saha yoddhavyam');
          writeln('asmin rana-samudyame');
          writeln;
          writeln('Arjuna berkata: Wahai Acyuta..., mohon');
          writeln('menempatkan kereta hamba di tengah-tengah');
          writeln('kedua belah pasukan. Dengan demikian, hamba');
          writeln('dapat melihat mereka semua, siapa yang hadir');
          writeln('ingin bertempur di sini dan dengan siapa hamba');
          writeln('harus bertempur dalam medan perang besar ini.');
        end;
    22: begin
          writeln('arjuna uvaca');
          writeln('senayor ubhayor madhye');
          writeln('ratham sthapaya me''cyuta');
          writeln;
          writeln('yavad etan nirikse''ham');
          writeln('yoddhu-kaman avasthitan');
          writeln('kair maya saha yoddhavyam');
          writeln('asmin rana-samudyame');
          writeln;
          writeln('Arjuna berkata: Wahai Acyuta..., mohon');
          writeln('menempatkan kereta hamba di tengah-tengah');
          writeln('kedua belah pasukan. Dengan demikian, hamba');
          writeln('dapat melihat mereka semua, siapa yang hadir');
          writeln('ingin bertempur di sini dan dengan siapa hamba');
          writeln('harus bertempur dalam medan perang besar ini.');
        end;
    23: begin
          writeln('yotsyamanan avekse''ham');
          writeln('ya ete''tra samagatah');
          writeln('dhartarastrasya durbuddher');
          writeln('yuddhe priya-cikirsavah');
          writeln;
          writeln('Biarlah hamba melihat mereka yang berkumpul');
          writeln('di medan perang ini dengan tujuan bertempur');
          writeln('karena ingin menyenangkan Putra Dhrtarastra');
          writeln('yang berhati jahat');
        end;
    24: begin
          writeln('sanjaya uvaca');
          writeln('evam ukto hrsikeso');
          writeln('gudakesena bharata');
          writeln('senayor ubhayor madhye');
          writeln('sthapayitva rathottamam');
          writeln;
          writeln('Sanjaya berkata: Wahai Maharaja Dhrtarastra,');
          writeln('setelah Arjuna berkata demikian, Sri Krsna');
          writeln('menempatkan kereta yang sangat gagah itu di');
          writeln('tengah-tengah antara kedua pasukan.');
        end;
    25: begin
          writeln('bhisma-drona-pramukhatah');
          writeln('sarvesam ca mahiksitam');
          writeln('uvaca partha pasyaitan');
          writeln('samavetan kurun iti');
          writeln;
          writeln('Di hadapan Bhisma, Drona dan raja-raja dunia');
          writeln('lainnya, Sri Krsna bersabda, "Wahai Partha,');
          writeln('lihatlah para Kuru yang telah berkumpul di sini."');
        end;
    26: begin
          writeln('tatrapasyat sthitan parthah');
          writeln('pitrn atha pitamahan');
          writeln('acaryan matulan bhratrn');
          writeln('putran pautran sakhims tatha');
          writeln;
          writeln('svasuran suhrdas caiva');
          writeln('senayor ubhayor api');
          writeln;
          writeln('Di sana, di tengah-tengah pasukan kedua belah');
          writeln('pihak Arjuna dapat melihat para Ayah, Guru,');
          writeln('Paman dari keluarga Ibu, Saudara, Putra, Cucu,');
          writeln('Kawan, Mertua dan orang yang mengharapkan');
          writeln('kesejahteraannya, semua hadir di sana.');
        end;
    27: begin
          writeln('tatrapasyat sthitan parthah');
          writeln('pitrn atha pitamahan');
          writeln('acaryan matulan bhratrn');
          writeln('putran pautran sakhims tatha');
          writeln;
          writeln('svasuran suhrdas caiva');
          writeln('senayor ubhayor api');
          writeln;
          writeln('Di sana, di tengah-tengah pasukan kedua belah');
          writeln('pihak Arjuna dapat melihat para Ayah, Guru,');
          writeln('Paman dari keluarga Ibu, Saudara, Putra, Cucu,');
          writeln('Kawan, Mertua dan orang yang mengharapkan');
          writeln('kesejahteraannya, semua hadir di sana.');
          readln;
          writeln('tan samiksya sa kaunteyah');
          writeln('sarvan bandhun avasthitan');
          writeln;
          writeln('krpaya parayavisto');
          writeln('visidann idam abravit');
          writeln;
          writeln('Melihat mereka semua yang adalah sanak');
          writeln('keluarganya, Arjuna terguguh rasa kasih sayang');
          writeln('dan dia berkata sebagai berikut:');
        end;
    28: begin
          writeln('tan samiksya sa kaunteyah');
          writeln('sarvan bandhun avasthitan');
          writeln;
          writeln('krpaya parayavisto');
          writeln('visidann idam abravit');
          writeln;
          writeln('Melihat mereka semua yang adalah sanak');
          writeln('keluarganya, Arjuna terguguh rasa kasih sayang');
          writeln('dan dia berkata sebagai berikut:');
          readln;
          writeln('arjuna uvaca');
          writeln('drstvemam sva-janam krsna');
          writeln('yuyutsum samupasthitam');
          writeln;
          writeln('sidanti mama gatrani');
          writeln('mukham ca parisusyati');
          writeln('vepathus ca sarire me');
          writeln('roma-harsas ca jayate');
          writeln;
          writeln('Arjuna berkata: Wahai Krsna, setelah melihat');
          writeln('semua sanak keluarga hadir di sini dengan');
          writeln('niat untuk bertempur, hamba merasa seluruh');
          writeln('aggota badan bergetar, mulut terasa kering,');
          writeln('seluruh tubuh menjadi gemetar dan bulu roma');
          writeln('pada merinding');
        end;
    29: begin
          writeln('arjuna uvaca');
          writeln('drstvemam sva-janam krsna');
          writeln('yuyutsum samupasthitam');
          writeln;
          writeln('sidanti mama gatrani');
          writeln('mukham ca parisusyati');
          writeln('vepathus ca sarire me');
          writeln('roma-harsas ca jayate');
          writeln;
          writeln('Arjuna berkata: Wahai Krsna, setelah melihat');
          writeln('semua sanak keluarga hadir di sini dengan');
          writeln('niat untuk bertempur, hamba merasa seluruh');
          writeln('aggota badan bergetar, mulut terasa kering,');
          writeln('seluruh tubuh menjadi gemetar dan bulu roma');
          writeln('pada merinding');

        end;
    30: begin
          writeln('gandivam sramsate hastat');
          writeln('tvak caiva paridahyate');
          writeln('na ca saknomy avathatum');
          writeln('bhramativa ca me manah');
          writeln;
          writeln('Kulit hamba terasa terbakar dan Gandiwa');
          writeln('terjatuh dari tangan hamba. Wahai Kesava,');
          writeln('hamba juga tidak mampu lagi berdiri, pikiran');
          writeln('hamba menjadi kacau balau.');
        end;
    31: begin
          writeln('nimittani ca pasyami');
          writeln('viparitani kesava');
          writeln('na ca sreyo''nupasyami');
          writeln('hatva svajanam ahave');
          writeln;
          writeln('Wahai Kesava, hamba melihat sebab-sebab');
          writeln('semuanya serba terbalik. Hamba tidak melihat');
          writeln('ada kebaikan apapun dengan membunuh para');
          writeln('anggota keluarga di dalam pertempuran ini.');
        end;
    32: begin
          writeln('na kankse vijayam krsna');
          writeln('na ca rajyam sukhani ca');
          writeln('kim no rajyena govinda');
          writeln('kim bhogair jivitena va');
          writeln;
          writeln('Wahai Krsna, hamba tidak menginginkan kemen-');
          writeln('angan, tidak juga kerajaan ataupun kesengangan.');
          writeln('Wahai Govinda, apa gunanya kerajaan, hidup dan');
          writeln('kesenangan-kesenangan seperti itu untuk kita?');
        end;
    33: begin
          writeln('yesam arthe kanksitam no');
          writeln('rajyam bhogah sukhani ca');
          writeln('ta ime''vasthita yuddhe');
          writeln('pranams tyaktva dhanani ca');
          writeln;
          writeln('Demi siapa kita menghasratkan kerajaan,');
          writeln('kemewahan dan berbagai kesenangan, mereka');
          writeln('semua dengan mengorbankan harta dan nyawa');
          writeln('kini berdiri disini siap untuk bertempur');
        end;
    34: begin
          writeln('acaryah pitarah putras');
          writeln('tathaiva ca pitamahah');
          writeln('matulah svasurah pautrah');
          writeln('syalah sambhandhinas tatha');
          writeln;
          writeln('Para guru, bapak-bapak, putra-putra, para kakek,');
          writeln('paman-paman, mertua-mertua, cucu-cucu,');
          writeln('ipar-ipar dan juga para sanak keluarga');
        end;
    35: begin
          writeln('etan na hantum icchami');
          writeln('ghnato''pi madhusudana');
          writeln('api trailokya-rajyasa');
          writeln('hetoh kim ni mahi-krte');
          writeln;
          writeln('Wahai Madhusudana, meskipun dengan imbalan');
          writeln('memperoleh kerajaan Triloka, hamba tidak');
          writeln('akan membunuh mereka walaupun mereka');
          writeln('menyerang hendak membunuh hamba. Lalu, apa');
          writeln('artinya dengan kerajaan di atas muka bumi ini?');
        end;
    36: begin
          writeln('nihatya dhartarastran nah');
          writeln('ka pritih syaj janardana');
          writeln('papam evasrayed asman');
          writeln('hatvaitan atatayinah');
          writeln;
          writeln('Wahai Janardana, kesukaan apa yang akan');
          writeln('kita peroleh dengan membunuh putra-putra');
          writeln('Dhrtarastra? Membasmi para pembunuh ini kita');
          writeln('hanya akan mendapatkan dosa-dosa');
        end;
    37: begin
          writeln('tasman narha vayam hantum');
          writeln('dhartarastran svabhandhavan');
          writeln('svajanam hi katham hatva');
          writeln('sukhinah syama madhava');
          writeln;
          writeln('Oleh karena itu, wahai Madhava, kita tidak');
          writeln('pantas membunuh putra-putra Dhrtarasta');
          writeln('yang adalah sanak keluarga sendiri. Bagaimana');
          writeln('mungkin kita bisa menjadi orang berbahagia');
          writeln('dengan membunuh sanak keluarga sendiri?');
        end;
    38: begin
          writeln('yady apy ete na pasyanti');
          writeln('lobhopahata-cetasah');
          writeln('kula-ksaya-krtam dosam');
          writeln('mitra-drohe ca patakam');
          writeln;
          writeln('katham na jneyam asmabhih');
          writeln('papad asman nivartitum');
          writeln('kula-ksaya-krtam dosam');
          writeln('prapasyadbhir janardana');
          writeln;
          writeln('walaupun orang-orang ini yang pikirannya telah');
          writeln('dikuasai oleh kelobaan tidak melihat dosa dalam');
          writeln('membunuh keluarga sendiri atau kehancuran');
          writeln('dalam bertengkar dengan kawan-kawan, wahai');
          writeln('Janardana..., kita yang dapat melihat bahwa');
          writeln('membinasakan sana keluarga adalah dosa,');
          writeln('demi menjauhkan diri dari dosa-dosa seperti itu,');
          writeln('mengapa kita tidak memahaminya?');
        end;
    39: begin
          writeln('yady apy ete na pasyanti');
          writeln('lobhopahata-cetasah');
          writeln('kula-ksaya-krtam dosam');
          writeln('mitra-drohe ca patakam');
          writeln;
          writeln('katham na jneyam asmabhih');
          writeln('papad asman nivartitum');
          writeln('kula-ksaya-krtam dosam');
          writeln('prapasyadbhir janardana');
          writeln;
          writeln('walaupun orang-orang ini yang pikirannya telah');
          writeln('dikuasai oleh kelobaan tidak melihat dosa dalam');
          writeln('membunuh keluarga sendiri atau kehancuran');
          writeln('dalam bertengkar dengan kawan-kawan, wahai');
          writeln('Janardana..., kita yang dapat melihat bahwa');
          writeln('membinasakan sana keluarga adalah dosa,');
          writeln('demi menjauhkan diri dari dosa-dosa seperti itu,');
          writeln('mengapa kita tidak memahaminya?');
        end;
    40: begin;
          writeln('kula-ksaye pranasyanti');
          writeln('kula-dharmah sanatanah');
          writeln('dharme naste kulam krtsnam');
          writeln('adharmo''bhibhavaty uta');
          writeln;
          writeln('Dengan hancurnya keluarga, maka seluruh');
          writeln('tradisi keluarga yang kekal dihancurkan');
          writeln('Dengan hancurnya tradisi suci, maka seluruh');
          writeln('keluarga akan terlibat dalam kebiasaan yang');
          writeln('bertentangan dengan dharma.');
        end;
    41: begin
          writeln('adharmabhibhavat krsna');
          writeln('pradusyanti kula-striyah');
          writeln('strisu dustasu varsneya');
          writeln('jayate varna-sankarah');
          writeln;
          writeln('Wahai Sri Krsna, dengan merajalelanya hal-hal');
          writeln('yang bertentangan dengan dharma maka kaum');
          writeln('wanita dalam keluarga akan menjadi tercemar');
          writeln('Duhai Varsneya, ketika tingkah laku para wanita');
          writeln('telah merosot, maka akan lahirlah keturunan');
          writeln('yang tidak diinginkan.');
        end;
    42: begin
          writeln('sankaro narakayaiva');
          writeln('kula-ghnanam kulasya ca');
          writeln('patanti pitaro hy esam');
          writeln('lupta-pindodaka-kriya');
          writeln;
          writeln('Anak-anak yang tidak diinginkan seperti itu');
          writeln('akan membawa para keluarga maupun para');
          writeln('penghancur keluarga itu sendiri ke neraka.');
          writeln('Lenyapnya tradisi mempersembahkan makanan');
          writeln('dan air kepada leluhur akan mengakibatkan');
          writeln('kejatuhan para leluhur.');
        end;
    43: begin
          writeln('dosair etaih kula-ghnanam');
          writeln('varna-sankara-karakaih');
          writeln('utsadyante jati-dharmah');
          writeln('kula-dharmas ca sasvatah');
          writeln;
          writeln('Akibat dosa-dosa para penghancur tradisi');
          writeln('keluarga yang menyebabkan lahirnya anak-anak');
          writeln('yang tidak diinginkan, maka tradisi-tradisi');
          writeln('keluarga yang suci-kekal dan kegiatan-kegiatan');
          writeln('yang mensejahterakan keluarga semuanya');
          writeln('menjadi binasa');
        end;
    44: begin
          writeln('utsanna-kula-dharmanam');
          writeln('manusyanam janardana');
          writeln('narake''niyatam vaso');
          writeln('bhavatity anususruma');
          writeln;
          writeln('Wahai Janardana, hamba mendengar bahwa');
          writeln('mereka yang tradisi-tradisi suci keluarganya');
          writeln('telah musnah akan tinggal di neraka dalam');
          writeln('waktu yang tidak dapat ditentukan');
        end;
    45: begin
          writeln('aho bata mahat-papam');
          writeln('kartum vyavasita vayam');
          writeln('yad rajya-sukha-lobhena');
          writeln('hantum svajanam udyatah');
          writeln;
          writeln('Aduh betapa menyedihkan bahwa kita');
          writeln('(yang mempunyai pengertian baik) sengan');
          writeln('bersiap-siap untuk melakukan kegiatan yang');
          writeln('sangat berdosa, hanya demi kelobaan menikmati');
          writeln('kesenangan akan kerajaan kita bertekad');
          writeln('membunuh keluarga sendiri.');
        end;
    46: begin
          writeln('yadi mam apratikaram');
          writeln('asastram sastra-panayah');
          writeln('dhartarastra rane hanyus');
          writeln('tan me ksemataram bhavet');
          writeln;
          writeln('Seandainya, bila di medan perang hamba tidak');
          writeln('membawa senjata dan tidak melawan, lalu');
          writeln('putra-putra Dhrtarastra membawa senjata di');
          writeln('tangan membunuh hamba, maka kematian');
          writeln('seperti itu akan lebih baik bagi hamba.');
        end;
    47: begin
          writeln('sanjaya uvaca');
          writeln('evam uktvarjunah sankhye');
          writeln('rathopastha upavisat');
          writeln('visrjya sasaram capam');
          writeln('soka-samvigna-manasah');
          writeln;
          writeln('Sanjaya berkata: setelah berkata seperti itu di');
          writeln('medan perang, Arjuna meletakkan busur dan');
          writeln('anak panahnya, lalu terduduk dalam kereta.');
          writeln('Pikirannya dipenuhi oleh kesedihan yang');
          writeln('mendalam.');
        end;
    end;
    readln;
  until (s=0) ;
end;

procedure a2;
var s:integer;
begin
  repeat
    clrscr;
    writeln('Pilih Sloka (1 - 72)');
    readln(s);
    case s of
    0: halt;
    1: begin
         writeln('sanjaya uvaca');
         writeln('tam tatha krpayavistam');
         writeln('asru-purnakuleksanam');
         writeln('visidantam idam vakyam');
         writeln('uvaca madhusudanah');
         writeln;
         writeln('Sanjaya berkata: Melihat Arjuna tertutupi oleh');
         writeln('rasa belas kasihan dan penyesalan, matanya');
         writeln('menjadi basah dipenuhi oleh air mata, maka');
         writeln('Madhusudana berkata sebagai berikut:');
       end;
    2: begin
         writeln('sri bhagavan uvaca');
         writeln('kutas tva kasmalam idam');
         writeln('visame samupasthitam');
         writeln('anarya-justam asvargyam');
         writeln('akirti-karam arjuna');
         writeln;
         writeln('Sri Krsna bersabda: Wahai Arjuna, dari mana');
         writeln('datangnya kekotoran ini menghinggapi dirimu');
         writeln('di saat-saat engkau menghadapi kesulitan');
         writeln('besar seperti ini? Tindakan itu bukanlah sifat');
         writeln('seorang Arya, tidak mengantarkan orang kepada');
         writeln('pencapaian surga, sebaliknya menjerumuskan');
         writeln('dirinya ke dalam kehinaan.');
       end;
    3: begin
         writeln('klaibyam ma sma gamah partha');
         writeln('naitat tvayy upapadyate');
         writeln('ksudram hrdaya-daurbalyam');
         writeln('tyaktvottistha parantapa');
         writeln;
         writeln('Wahai Partha, janganlah menyerah kepada');
         writeln('kelemahan ini. Hal ini sama sekali tidak pantas');
         writeln('bagimu. Tinggalkanlah kelemahan hati yang');
         writeln('tidak ada artinya itu, dan bangkitlah, wahai');
         writeln('Arjuna');
       end;
    4: begin
         writeln('arjuna uvaca');
         writeln('katham bhismam aham sankhye');
         writeln('dronam ca madhusudana');
         writeln('isubhih pratiyotsyami');
         writeln('pujarhav ari-sudana');
         writeln;
         writeln('Arjuna berkata: Wahai Madhusudana, bagaimana');
         writeln('hamba mampu melepaskan anak panah di');
         writeln('dalam pertempuran, O Arisudana..., ke arah');
         writeln('orang-orang yang hamba patut sembah seperti');
         writeln('kakek Bhisma dan Guru Drona?');
       end;
    5: begin
         writeln('gurun ahatva hi mahanubhavan');
         writeln('sreyo bhoktum bhaiksyam apiha loke');
         writeln('hatvartha-kamams tu gurun ihaiva');
         writeln('bhunjiya bhogan rudhira-pradigdhan');
         writeln;
         writeln('Daripada membunuh para guru yang sesung-');
         writeln('guhnya adalah tokoh-tokoh yang sangat agung,');
         writeln('lebih baik hamba hidup di dunia ini dengan cara');
         writeln('mengemis. Oleh karena itu, dengan membunuh');
         writeln('mereka yang menginginkan keuntungan duniawi,');
         writeln('tetapi mereka tetap adalah para guru, maka');
         writeln('kepuasan itu bagaikan menikmati makanan yang');
         writeln('bergelimangan dengan darah.');
       end;
    6: begin
         writeln('na caitad vidmah kataran no gariyo');
         writeln('yad va jayema yadi va no jayeyuh');
         writeln('yan eva hantva na jijivisamas');
         writeln('te''vasthitah pramukhe dhartarastrah');
         writeln;
         writeln('Hamba juga tidak mengerti pilihan mana');
         writeln('yang lebih baik, kami harus bertempur');
         writeln('atau tidak bertempur? Dan kami juga tidak');
         writeln('mengerti, apakah kami mengalahkan mereka');
         writeln('ataukan mereka mengalahkan kami? Dengan');
         writeln('membunuh putra-putra kesayangan Dhrtarastra');
         writeln('ini sesungguhnya hamba tidak ingin hidup,');
         writeln('sedangkan sekarang mereka berdiri dihadapan');
         writeln('kami dalam keadaan siap bertempur');
       end;
    7: begin
         writeln('karpanya-doso''pahata-svabhavah');
         writeln('prcchami tvam dharma-sammudha-cetah');
         writeln('yac chreyah syan niscitam bruhi tan me');
         writeln('sisyas te''ham sadhi mam tvam prapannam');
         writeln;
         writeln('Kesadaran hamba menjadi sangat lemah dan');
         writeln('kalut dipenuhi kebingungan tentang kewajiban');
         writeln('hamba, maka hamba bertanya kepada Anda, ber-');
         writeln('itahukanlah dengan pasti kepada hamba yang');
         writeln('mana lebih baik? Hamba adalah murid Anda,');
         writeln('berikanlah pelajaran kepada hamba, dan hamba');
         writeln('menyerahkan diri sepenuhnya kepada Anda.');
       end;
    8: begin
         writeln('na hi prapasyami mamapanudyad');
         writeln('yac chokam ucchosanam indriyanam');
         writeln('avapya bhumav asapatnam rddham');
         writeln('rajyam suranam api cadhipatyam');
         writeln;
         writeln('Walau tanpa halangan sedikit pun mendapatkan');
         writeln('kekuasaan dan kerajaan di atas muka bumi ini');
         writeln('yang dipenuhi oleh segala jenis kemakmuran');
         writeln('bagaikan kemuliaan para dewa di surga,');
         writeln('namun hamba tetap tidak dapat melihat suatu');
         writeln('cara untuk menghilangkan kesedihan ini yang');
         writeln('menyebabkan indria-indria hamba menjadi');
         writeln('kering.');
       end;
    9: begin
         writeln('sanjaya uvaca');
         writeln('evam uktva hrsikesam');
         writeln('gudakesah parantapah');
         writeln('na yotsya iti govindam');
         writeln('uktva tusnim babhuva ha');
         writeln;
         writeln('Sanjaya berkata: Wahai Maharaja Dhrtarastra...,');
         writeln('setelah Arjuna berkata seperti itu kepada Krsna,');
         writeln('lalu Arjuna berkata kepada Govinda, "Hamba');
         writeln('tidak akan bertempu...." Setelah berkata seperti');
         writeln('itu dengan jelas, Arjuna lalu terdiam.');
       end;
    10: begin
          writeln('tam uvaca hrsikesah');
          writeln('prahasann iva bharata');
          writeln('senayor ubhayor madhye');
          writeln('visidantam idam vacah');
          writeln;
          writeln('Wahai keturunan keluarga Bharata, Maharaja');
          writeln('Dhrtarastra..., kepada Arjuna yang sedang');
          writeln('berada dalam kesedihan di tengah-tengah antara');
          writeln('kedua pasukan perang, lalu sambil tersenyum Sri');
          writeln('Krsna berkata seperti ini:');
        end;
    11: begin
          writeln('sri-bhagavan uvaca');
          writeln('asocyan anvasocas tvam');
          writeln('prajna-vadams ca bhasase');
          writeln('gatasun agatums ca');
          writeln('nanusocanti panditah');
          writeln;
          writeln('Tuhan Yang Maha Esa bersabda, Engkau');
          writeln('berbicara dengan kata-kata yang sangat bijak,');
          writeln('tetapi pada saat yang sama engkau menyesal');
          writeln('terhadap sesuatu yang tidak patut disesalkan.');
          writeln('Orang-orang bijaksana tidak akan bersedih');
          writeln('terhadap mereka yang sudah meninggal maupun');
          writeln('terhadap mereka yang masih hidup.');
        end;
    12: begin
          writeln('na tv evaham jatu nasam');
          writeln('na tvam neme janadhipah');
          writeln('na caiva na bhavisyamah');
          writeln('sarve vayam atah param');
          writeln;
          writeln('Tidak pernah terjadi seperti ini bahwa pada');
          writeln('masa lampau Aku tidak pernah ada, engkau');
          writeln('tidak ada, dan semua raja-maharaja ini tidak');
          writeln('pernah ada. Dan juga tidak pernah terjadi seperti');
          writeln('ini bahwa kita semua tidak akan ada.');
        end;
    13: begin
          writeln('dehino''smin yatha dehe');
          writeln('kaumaram yauvanam jara');
          writeln('tatha dehantara-praptir');
          writeln('dhiras tatra na muhyati');
          writeln;
          writeln('Sebagaimana Sang Roh di dalam badan ini');
          writeln('mengalami perputaran dari masa kanak-kanak');
          writeln('ke masa muda dan masa tua, seperti itulah');
          writeln('badan lain didapatkan setelah meninggal.');
          writeln('Orang-orang bijaksana sama sekali tidak akan');
          writeln('terbingungkan oleh hal itu.');
        end;
    14: begin
          writeln('matra-sparsas tu kaunteya');
          writeln('sitosna-sukha-dukha-dah');
          writeln('agamapayino''nityas');
          writeln('tams titiksasva bharata');
          writeln;
          writeln('Wahai putra Kunti, panas dan dingin, suka dan');
          writeln('duka, semua itu terjadi akibat sentuhan indria');
          writeln('dengan objeknya. Semuanya datang dan pergi');
          writeln('serta bersifat sementara. Wahai Arjuna...,');
          writeln('terimalah semua hal itu tanpa tergoyahkan.');
        end;
    15: begin
          writeln('yam hi na vyathayanty ete');
          writeln('purusam purusarsabha');
          writeln('sama-duhkha-sukham dhiram');
          writeln('so''mrtatvaya kalpate');
          writeln;
          writeln('Wahai Arjuna, yang terbaik di antara manusia,');
          writeln('mereka yang dapat menerima sama antara suka');
          writeln('dan duka, yang tabah dan tidak tergoyahkan oleh');
          writeln('semua ini, mereka sesungguhnya memenuhi');
          writeln('syarat untuk mencapai pembebasan dari');
          writeln('kesengsaraan.');
        end;
    16: begin
          writeln('nasato vidyate bhavo');
          writeln('nabhavo vidyate satah');
          writeln('ubhayor api drsto''ntas');
          writeln('tv anayos tattva-darsibhih');
          writeln;
          writeln('Hal-hal yang tidak kekal, tidak pernah ada, hal-hal');
          writeln('yang kekal, tidak pernah tidak ada. Orang-orang');
          writeln('suci yang telah melihat kebenaran dapat');
          writeln('mengetahui kenyataan dari kedua hal itu setelah');
          writeln('mendalami keduanya.');
        end;
    17: begin
          writeln('avinasi tu tad viddhi');
          writeln('yena sarvam idam tatam');
          writeln('vinasam avyayasyaya');
          writeln('na kascit kartum arhati');
          writeln;
          writeln('Usahakanlah untuk memahami tentang ia');
          writeln('yang bersifat kekal, ia yang meliputi seluruh');
          writeln('jagat raya ini. Tidak seorangpun yang mampu');
          writeln('membinasakan dia yang tidak terbinasakan.');
        end;
    18: begin
          writeln('antavanta ime deha');
          writeln('nityasyoktah saririnah');
          writeln('anasino''prameyasya');
          writeln('tasmad yudhyasva bharata');
          writeln;
          writeln('Dikatakan bahwa badan jasmani ini dapat');
          writeln('dimusnahkan, sedangkan ia yang tinggal di');
          writeln('dalam badan adalah bersifat kekal. Ia tidak');
          writeln('dapat diukur dan bersifat kekal abadi. Oleh');
          writeln('karena itu, wahai putra keluarga Bharata,');
          writeln('bertempurlah.');
        end;
    19: begin
          writeln('ya enam vetti hantaram');
          writeln('yas cainam manyate hatam');
          writeln('ubhau tau na vijanito');
          writeln('nayam hanti na hanyate');
          writeln;
          writeln('Dia yang berpendapat bahwa dirinya dapat');
          writeln('membunuh atau dapat terbunuh, sesungguhnya');
          writeln('keduanya tidak mengetahui bahwa Sang');
          writeln('Roh tidak dapat membunuh dan tidak dapat');
          writeln('terbunuh.');
        end;
    20: begin
          writeln('na jayate mriyate va kadacin');
          writeln('nayam bhutva bhavita va na bhuyah');
          writeln('ajo nityah sasvato ''yam purano');
          writeln('na hanyate hanyamane sarire');
          writeln;
          writeln('Kapan pun Sang Atma tidak pernah dilahirkan');
          writeln('dan juga tidak pernah mati. Dia tidak diciptakan');
          writeln('pada masa lampau, pada masa sekarang');
          writeln('dan pada masa yang akan datang. Dia tidak');
          writeln('dilahirkan, kekal ada selamanya dan bersifat');
          writeln('kekal abadi. Dia tidak terbunuh ketika badan');
          writeln('jasmani terbunuh.');
        end;
    21: begin
          writeln('vedavinasinam nityam');
          writeln('ya enam ajam avyayam');
          writeln('katham sa purusah partha');
          writeln('kam ghatayati hanti kam');
          writeln;
          writeln('Orang yang mengetahui bahwa Sang Roh');
          writeln('tidak dapat dibinasakan, bersifat kekal, tidak');
          writeln('terlahirkan dan tidak berubah, wahai Partha,');
          writeln('bagaimana mungkin orang itu menganggap');
          writeln('dirinya dapat membunuh atau menyebabkan');
          writeln('orang membunuh seseorang?');
        end;
    22: begin
          writeln('vasamsi jirnani yatha vihaya');
          writeln('navani grhnati naro''parani');
          writeln('tatha sarirani vihaya jirnany');
          writeln('anyani samyati navani dehi');
          writeln;
          writeln('Sebagaimana halnya seseorang menanggalkan');
          writeln('pakaian yang sudah usang dan mengenakan');
          writeln('pakaian yang baru, seperti itu pula Sang Roh');
          writeln('meninggalkan badan jasmani yang sudah tidak');
          writeln('berguna dan memasuki badan jasmani yang');
          writeln('baru.');
        end;
    23: begin
          writeln('nainam chindanti sastrani');
          writeln('nainam dahati pavakah');
          writeln('na cainam kledayanty apo');
          writeln('na sosayati marutah');
          writeln;
          writeln('Senjata-senjata tidak dapat memotong Sang');
          writeln('Roh, api tidak dapat membakarnya, air tidak');
          writeln('dapat membasmi Sang Roh ini, dan juga angin');
          writeln('tidak dapat mengeringkannya');
        end;
    24: begin
          writeln('acchedyo''yam adahyo''yam');
          writeln('akledyo''sosya eva ca');
          writeln('nityah sarva-gatah sthanur');
          writeln('acalo''yam sanatanah');
          writeln;
          writeln('Roh ini tidak dapat dipotong-potong, ia tidak');
          writeln('dapat dibakar, tidak dapat dibasahi (oleh air)');
          writeln('dan juga tidak dapat dikeringkan (oleh angin)');
          writeln('karena ia bersifat kekal, berada secara sempurna');
          writeln('dimana-mana, tidak pernah keluar dari sifat');
          writeln('aslinya, bersifat tetap serta ada kekal untuk');
          writeln('selamanya.');
        end;
    25: begin
          writeln('avyakto''yam acintyo''yam');
          writeln('avikaryo''yam ucyate');
          writeln('tasmad evam viditvainam');
          writeln('nanusocitum arhasi');
          writeln;
          writeln('Roh ini tidak dapat dilihat, tidak dapat dipikirkan');
          writeln('dan juga dikatakan bahwa roh ini tidak berubah.');
          writeln('Oleh karena itu, setelah mengetahui dengan baik');
          writeln('tentang kesejatian Sang Roh ini, maka engkau');
          writeln('hendaknya jangan menyesal karena badan.');
        end;
    26: begin
          writeln('atha cainam nitya-jatam');
          writeln('nityam va manyase mrtam');
          writeln('tathapi tvam maha-baho');
          writeln('nainam socitum arhasi');
          writeln;
          writeln('Wahai Arjuna yang berlengan perkasa...,');
          writeln('jika engkau berpendapat bahwa Sang Roh');
          writeln('senantiasa dilahirkan dan mati, maka tetap saja');
          writeln('engkau tidak patut menyesal.');
        end;
    27: begin
          writeln('jitasya hi dhruvor mrtyur');
          writeln('dhruvam janma mrtasya ca');
          writeln('tasmad apariharye''rthe');
          writeln('na tvam socitum arhasi');
          writeln;
          writeln('(Sebab) Semua yang dilahirkan pasti diikuti oleh');
          writeln('kematian, dan secara pasti kematian juga diikuti');
          writeln('oleh kelahiran. Oleh karena itu, terhadap hal-hal');
          writeln('yang tidak dapat dihindari, maka hendaknya');
          writeln('engkau jangan menyesal');
        end;
    28: begin
          writeln('avyaktadini bhutani');
          writeln('vyakta-madhyani bharata');
          writeln('avyakta-nidhanany eva');
          writeln('tatra ka paridevana');
          writeln;
          writeln('Wahai Arjuna, sebelum dilahirkan semua');
          writeln('makhluk hidup tidak terwujud, dan setelah');
          writeln('kematian kembali tidak terwujud, ia terwujud');
          writeln('hanya pada pertengahan. Mempertimbangkan');
          writeln('hal itu apa yang perlu disesalkan?');
        end;
    29: begin
          writeln('ascarya-vat pasyati kascid evam');
          writeln('ascarya-vad vadati tathaiva canyah');
          writeln('ascarya-vac cainam anyah srnoti');
          writeln('srutvapy-enam veda na caive kascit');
          writeln;
          writeln('Ada yang melihat Sang Roh sebagai sesuatu');
          writeln('yang mengherankan, ada yang menjelaskan');
          writeln('sebagai sesuatu yang mengherankan, dan');
          writeln('yang lain ada pula mendengarkannya sebagai');
          writeln('sesuatu yang mengherankan, sedangkan yang');
          writeln('lain setelah mendengar pun tetap tidak dapat');
          writeln('mengerti perihal Sang Roh ini.');
        end;
    30: begin
          writeln('dehi nityam avadhyo''yam');
          writeln('dehe sarvasya bharata');
          writeln('tasmat sarvani bhutani');
          writeln('na tvam socitum arhasi');
          writeln;
          writeln('Wahai keturunan Bharata, Sang Roh yang berada');
          writeln('di dalam badan bersifat kekal dan tidak pernah');
          writeln('dapat dibunuh. Oleh karena itu, engkau tidak');
          writeln('patut bersedih hati untuk makhluk manapun.');
        end;
    31: begin
          writeln('sva-dharmam api caveksya');
          writeln('na vikampitum arhasi');
          writeln('dharmyaddhi yuddhac chreyo''nyat');
          writeln('ksatriyasya na vidyate');
          writeln;
          writeln('Setelah menyadari kewajiban sucimu sebagai');
          writeln('seorang ksatria, maka engkau hendaknya jangan');
          writeln('menjadi tergoyahkan. Sesungguhnya bagi');
          writeln('seorang ksatria, tidak ada kewajiban yang lebih');
          writeln('tinggi daripada kewajiban bertempur.');
        end;
    32: begin
          writeln('yadrcchaya copapannam');
          writeln('svarga-dvaram apavrtam');
          writeln('sukhinah ksatriyah partha');
          writeln('labhante yuddham idrsam');
          writeln;
          writeln('Mendapatkan kesempatan bertempur seperti');
          writeln('itu tanpa mencarinya menyebabkan pintu');
          writeln('surga terbuka lebar-lebar (bagimu). Wahai');
          writeln('Putra Prtha..., berbahagialah para ksatria yang');
          writeln('mendapatkan kesempatan bertempur seperti itu.');
        end;
    33: begin
          writeln('atha cet tvam imam dharmyam');
          writeln('sangramam na karisyasi');
          writeln('tatah sva-dharmam kirtim ca');
          writeln('hitva papam avapsyasi');
          writeln;
          writeln('Sekarang, jika engkau tidak akan melaksanakan');
          writeln('kewajiban bertempur di jalan dharma ini, dengan');
          writeln('menolak kewajibanmu dan (mengabaikan) nama');
          writeln('baikmu, maka engkau akan mendapatkan dosa.');
        end;
    34: begin
          writeln('akirtim capi bhutani');
          writeln('kathayisyanti te''vyayam');
          writeln('sambhavitasya cakirtir');
          writeln('maranad atiricyate');
          writeln;
          writeln('Nama burukmu akan dibicarakan oleh semua');
          writeln('orang untuk selamanya. Dan bagi ksatria');
          writeln('terhormat, nama buruk adalah lebih jelek');
          writeln('daripada kematian.');
        end;
    35: begin
          writeln('bhayad ranad uparatam');
          writeln('mamsyante tvam maha-rathah');
          writeln('yesam ca tvam bahu-mato');
          writeln('bhutva yasyasi laghavam');
          writeln;
          writeln('Para ksatria agung akan menganggap engkau');
          writeln('melarikan diri dari medan perang karena');
          writeln('ketakutan. Dan mereka yang sangat menghargai');
          writeln('kemuliaanmu akhirnya akan meremehkan.');
        end;
    36: begin
          writeln('avacya-vadams ca bahun');
          writeln('vadisyanti tavahitah');
          writeln('nindantas tava samarthyam');
          writeln('tato dukhataram nu kim');
          writeln;
          writeln('Musuh-musuhmu akan meragukan keksatri-');
          writeln('aanmu dan mereka akan mengeluarkan segala');
          writeln('jenis kata-kata yang tidak patut diucapkan.');
          writeln('Dengan demikian, adakah hal lain yang lebih');
          writeln('menyengsarakan daripada itu?');
        end;
    37: begin
          writeln('hato va prapsyasi svargam');
          writeln('jitva va bhoksyase mahim');
          writeln('tasmad utthistha kaunteya');
          writeln('yuddhaya krta-niscayah');
          writeln;
          writeln('Wahai Putra Kunti, jika engkau akan terbunuh');
          writeln('di medan perang, maka engkau akan mencapai');
          writeln('surga. Atau, jika engkau akan menang, maka');
          writeln('engkau akan menikmati kerajaan di dunia. Oleh');
          writeln('karena itu, bangunlah dan pastikan dirimu untuk');
          writeln('bertempur.');
        end;
    38: begin
          writeln('sukha-duhkhe same krtva');
          writeln('labhalabhau jayajayau');
          writeln('tato yuddhaya yujyasva');
          writeln('naivam papam avapsyasi');
          writeln;
          writeln('Terimalah dengan cara yang sama antara suka');
          writeln('dan duka, untung dan rugi, menang ataupun');
          writeln('kalah. Untuk itu, sibukkaanlah dirimu di dalam');
          writeln('peperangan. Dengan demikian engkau tidak');
          writeln('akan pernah dipengaruhi oleh dosa.');
        end;
    39: begin
          writeln('esa te''bhihita sankhye');
          writeln('buddhir yoge tv imam srnu');
          writeln('buddhya yukto yaya partha');
          writeln('karma-bandham prahasyasi');
          writeln;
          writeln('Aku sudah menjelaskan pengetahuan Sankhya');
          writeln('atau pelajaran analisis kepadamu. Sekarang');
          writeln('dengarkanlah pengetahuan tentang Karma Yoga');
          writeln('atau melakukan pekerjaan tanpa mengharapkan');
          writeln('pahala. Melalui kesadaran persamaan seperti');
          writeln('itu, wahai Arjuna, engkau akan terbebaskan dari');
          writeln('ikatan karma.');
        end;
    40: begin
          writeln('nehabhikrama-naso''sti');
          writeln('pratyabayo na vidyate');
          writeln('sv-alpam apy asya dharmasya');
          writeln('trayate mahato bhayat');
          writeln;
          writeln('Di dalam awal pelaksanaan Karma Yoga');
          writeln('ini, (sama sekali) tidak ada kerugian, dan');
          writeln('pelaksanaannya pun tidak memberikan hasil');
          writeln('terbalik. Kemajuan sedikit pun dalam menempuh');
          writeln('jalan ini dapat melindungi seseorang dari mara');
          writeln('bahaya maha besar');
        end;
    41: begin
          writeln('vyavasayatmika buddhir');
          writeln('ekeha kuru-nandana');
          writeln('bahu-sakha hy anantas ca');
          writeln('buddhayo''vyavasayinam');
          writeln;
          writeln('Wahai Arjuna, di dalam pelaksanaan yoga ini');
          writeln('kesadaran orang menjadi mantap dan tertuju');
          writeln('pada yang Satu. Sedangkan mereka yang tidak');
          writeln('memusatkan tujuannya pada yang Satu, maka');
          writeln('kecerdasan mereka akan bercabang-cabang');
          writeln('sangat banyak.');
        end;
    42: begin
          writeln('yam imam puspitam vacam');
          writeln('pravadanty avipascitah');
          writeln('veda-vada-ratah partha');
          writeln('nanyad astiti vadinah');
          writeln;
          writeln('Orang yang memiliki pengetahuan sangat');
          writeln('terbatas akan sangat tertarik pada kata-kata');
          writeln('berbunga, menjadi lelap di dalam ajaran');
          writeln('ajaran Veda yang menjanjikan keberhasilan');
          writeln('keinginan-keinginan. Wahai Arjuna, mereka akan');
          writeln('mengatakan bahwa selain pemuasan keinginan,');
          writeln('tidak ada hal lain lagi (yang perlu dicari).');
        end;
    43: begin
          writeln('kamatmanah svarga-para');
          writeln('janma-karma-phala-pradam');
          writeln('kriya-visesa-bahulam');
          writeln('bhogaisvarga-gatim prati');
          writeln;
          writeln('Wahai Arjuna..., mereka yang menginginkan');
          writeln('pemuasan keinginan-keinginan, maka mereka');
          writeln('akan menjadikan surga sebagai tujuan akhirnya');
          writeln('mereka akan terikat pada kegiatan-kegiatan');
          writeln('yang membuahkan pahala-pahala, lelap di dalam');
          writeln('pelaksanaan upacara-upacara khusus demi');
          writeln('mendapatkan kelahiran yang baik, kekayaan dan');
          writeln('kemashyuran duniawi.');
        end;
    44: begin
          writeln('bhogaisvarya-prasaktanam');
          writeln('tayapahrta-cetasam');
          writeln('vyavasayatmika buddhih');
          writeln('samadhau na vidhiyate');
          writeln;
          writeln('Mereka yang pikirannya telah dikalahkan oleh');
          writeln('kata-kata berbunga Veda menjadi sangat terikat');
          writeln('pada kenikmatan dan kekuasaan duniawi.');
          writeln('Kecerdasannya tidak akan terpusat pada yang');
          writeln('Satu, dan tidak akan bisa mantap dalam berbakti');
          writeln('kepada Tuhan Yang Maha Esa.');
        end;
    45: begin
          writeln('trai-gunya-visaya veda');
          writeln('nistrai-gunyo bhavarjuna');
          writeln('nirdvandvo nitya-sattva-stho');
          writeln('niryoga-ksema atmavan');
          writeln;
          writeln('Ajaran-ajaran Veda sebagian besar mengajarkan');
          writeln('tentang tiga sifat alam: kebaikan, kenafsuan');
          writeln('dan kebodohan. Wahai Arjuna, atasilah ketiga');
          writeln('sifat alam itu. Bebaskanlah dirimu dari dualisme,');
          writeln('tempatkan kesadaranmu senantiasa di dalam');
          writeln('tingkat kebaikan, bebaskan diri dari keinginan');
          writeln('untuk mendapatkan pahala dan perlindungan,');
          writeln('dan mantaplah di dalam Sang Diri.');
        end;
    46: begin
          writeln('yavan artha udapane,');
          writeln('sarvatah samplutodake');
          writeln('tavan sarvesu vedesu,');
          writeln('brahmanasya vijanatah');
          writeln;
          writeln('Seberapa tujuan yang diperlukan oleh kolam ke-');
          writeln('cil dalam segala hal dapat segera dipenuhi oleh');
          writeln('sumber air yang besar. Seperti itu pula, segala');
          writeln('tujuan ajaran Veda dapat dicapai oleh orang suci');
          writeln('yang telah menguasai tujuan utama dari Veda.');
         end;
    47: begin
          writeln('karmany evadhikaras te');
          writeln('ma phalesu kadacana');
          writeln('ma karma-phala-hetur bhur');
          writeln('ma te sango''stv akarmani');
          writeln;
          writeln('Hakmu hanyalah pada pelaksanaan tugas');
          writeln('kewajiban, dan sama sekali tidak pada pahala');
          writeln('dari tugas kewajiban yang engkau lakukan.');
          writeln('Jangan beranggapan engkau menjadi penyebab');
          writeln('dari hasil perbuatan, dan jangan menjadi terikat');
          writeln('untuk tidak melakukan tuga kewajibanmu.');
        end;
    48: begin
          writeln('yoga-sthah kuru karmani');
          writeln('sangam tyaktva dhananjaya');
          writeln('siddhy-asiddhyoh samo bhutva');
          writeln('samatvam yoga ucyate');
          writeln;
          writeln('Wahai Dhananjaya, lakukanlah segala tugas');
          writeln('kewajibanmu dengan memantapkan diri di');
          writeln('dalam yoga, tinggalkan segala keterikatan pada');
          writeln('hasil dari segala perbuatan, seimbangkan diri di');
          writeln('dalam keberhasilan maupun kegagalan, sebab');
          writeln('sikap seimbang seperti itulah yang dinamakan');
          writeln('yoga.');
        end;
    49: begin
          writeln('durena hy avaram karma');
          writeln('buddhi-yogad dhananjaya');
          writeln('buddhau saranam anviccha');
          writeln('krpanah phala-hetavah');
          writeln;
          writeln('Wahai Dhananjaya, jauhkanlah perbuatan-');
          writeln('perbuatan rendah melalui kesadaran keseimban-');
          writeln('gan seperti itu. Berlindunglah pada kesadaran');
          writeln('seperti itu, oleh karena orang yang menginginkan');
          writeln('pahala dari perbuatan-perbuatannya');
          writeln('sesungguhnya adalah orang yang pelit.');
        end;
    50: begin
          writeln('buddhi-yukto jahatiha');
          writeln('ubhe sukrta-duskrte');
          writeln('tasmad yogaya yujyasva');
          writeln('yogah karmasu kausalam');
          writeln;
          writeln('Orang yang mempunyai kesadaran keseimban-');
          writeln('gan membebaskan dirinya dari perbuatan baik');
          writeln('dan buruk dalam kehidupan manusia ini. Oleh');
          writeln('karena itu, lelapkanlah dirimu di dalam yoga');
          writeln('keseimbangan, sebab mempraktikkan yoga di');
          writeln('dalam segala perbuatan adalah kecerdasan.');
        end;
    51: begin
          writeln('karma-jam buddhi-yukta hi');
          writeln('phalam tyaktva manisinah');
          writeln('janma-bandha-vinirmuktah');
          writeln('padam gacchanty anamayam');
          writeln;
          writeln('Orang-orang suci membebaskan dirinya dari');
          writeln('pahala-pahala yang lahir dari perbuatan dengan');
          writeln('menekuni bakti kepada Tuhan Yang Maha Esa');
          writeln('dalam kesadaran suci. Mereka terbebaskan');
          writeln('dari perputaran kelahiran dan kematian dan');
          writeln('mencapai alam kekekalan.');
        end;
    52: begin
          writeln('yada te moha-kalilam');
          writeln('buddhir vyatitarisyati');
          writeln('tada gantasi nirvedam');
          writeln('srotavyasya srutasya ca');
          writeln;
          writeln('Ketika kecerdasanmu menyeberangi hutan');
          writeln('khayalan yang lebat, maka pada saat itu engkau');
          writeln('akan sampai pada keadaan tidak peduli');
          writeln('terhadap segala sesuatu yang telah didengar');
          writeln('dan segala sesuatu yang akan didengar.');
        end;
    53: begin
          writeln('sruti-vipratipanna te');
          writeln('yada sthasyati niscala');
          writeln('samadhav acala buddhis');
          writeln('tada yogam avapsyasi');
          writeln;
          writeln('Ketika pikiranmu yang tergoyahkan oleh');
          writeln('berbagai perbedaan yang terdapat di dalam');
          writeln('kitab suci akan menjadi mantap dan terlelap di');
          writeln('dalam Tuhan Yang Maha Esa, maka pada saat');
          writeln('itu engkau akan mencapai tingkatan yoga.');
        end;
    54: begin
          writeln('arjuna uvaca');
          writeln('sthita-prajnasya ka bhasa');
          writeln('samadhi-sthasya kesava');
          writeln('sthita-dhih kim prabhaseta');
          writeln('kim asita vrajeta kim');
          writeln;
          writeln('Arjuna bertanya,"Wahai Kesava Krsna,');
          writeln('bagaimana ciri-ciri orang yang kesadarannya');
          writeln('sudah terlelap di dalam Tuhan Yang Maha Esa?');
          writeln('Bagaimana tutur kata orang-orang yang sudah');
          writeln('mencapai tingkatan kesadaran yang mantap?');
          writeln('Bagaimana cara duduknya? (Dan) Bagaimana');
          writeln('cara berjalannya?"');
        end;
    55: begin
          writeln('sri-bhagavan uvaca');
          writeln('prajahati yada kaman');
          writeln('sarvan partha mano-gatan');
          writeln('atmany evatmana tustah');
          writeln('sthita-prajnas tadocyate');
          writeln;
          writeln('Sri Bhagavan bersabda,"Wahai Partha...,');
          writeln('ketika seorang Sadhaka berhasil mengatasi');
          writeln('segala jenis keinginan duniawi yang memasuki');
          writeln('pikirannya, dan melalui Sang Diri berpuas hati');
          writeln('hanya di dalam Sang Diri, maka pada saat itu');
          writeln('dikatakan ia sudah mencapai tingkat kesadaran');
          writeln('terlelap di dalam Tuhan Yang Maha Esa.');
        end;
    56: begin
          writeln('duhkhesv anudviga-manah');
          writeln('sukhesu vigata-sprhah');
          writeln('vita-raga-bhaya-krodhah');
          writeln('sthita-dhir munir ucyate');
          writeln;
          writeln('Orang yang pikirannya tidak tergoyahkan di');
          writeln('dalam duka, tidak riang berlebihan di dalam');
          writeln('keadaan suka, bebas dari ikatan, kecemasan dan');
          writeln('kemarahan, dia disebut sebagai seoran muni');
          writeln('yang memiliki kesadaran yang mantap.');
        end;
    57: begin
          writeln('yah sarvatranabhisnehas');
          writeln('tat tat prapya subhasubham');
          writeln('nabhinandati na dvesti');
          writeln('tasya prajna pratisthita');
          writeln;
          writeln('Di mana-mana di alam material ini, orang yang');
          writeln('tidak terikat pada hal-hal baik dan buruk yang');
          writeln('diperolehnya, tidak memuji dan tidak mencemoh,');
          writeln('(orang seperti itu) kesadarannya sudah menjadi');
          writeln('mantap sempurna.');
        end;
    58: begin
          writeln('yada samharate cayam');
          writeln('kurmo nganiva sarvasah');
          writeln('indriyanindriyarthebhyas');
          writeln('tasya prajna pratisthita');
          writeln;
          writeln('Sebagaimana kura-kura menarik');
          writeln('anggota-anggota badannya dari seluruh arah,');
          writeln('seperti itu pula ketika orang menari seluruh');
          writeln('indrianya dari objek-objek indria, maka pada saat');
          writeln('itu kesadarannya menjadi mantap sempurna.');
        end;
    59: begin
          writeln('visaya vinivartante');
          writeln('niraharasya dehinah');
          writeln('rasa-varjam raso ''py asya');
          writeln('param drstva nivartate');
          writeln;
          writeln('Mereka yang sudah menjauhkan indria-indrianya');
          writeln('dari objek-objek indria, barangkali objek');
          writeln('indria-indria terjauhkan, tetapi rasa kepuasan');
          writeln('indria masih tetap ada. Akan tetapi, dengan');
          writeln('mengalami rasa kepuasan yang maha tinggi');
          writeln('di dalam Tuhan Yang Maha Esa, maka rasa');
          writeln('kepuasan duniawi menjadi tidak ada.');
        end;
    60: begin
          writeln('yatato hy api kaunteya');
          writeln('purusasya vipascitah');
          writeln('indriyani pramathini');
          writeln('haranti prasabham manah');
          writeln;
          writeln('Sebab, wahai Putra Dewi Kunti, pikiran');
          writeln('orang-orang bijaksana yang sedang berusaha');
          writeln('untuk mengendalikan indria-indrianya pun dapat');
          writeln('dibawa lari secara paksa oleh indria-indria yang');
          writeln('sangat kuat itu.');
        end;
    61: begin
          writeln('tani sarvani samyamya');
          writeln('yukta asita mat-patah');
          writeln('vase hi yasyendriyani');
          writeln('tasya prajna pratisthita');
          writeln;
          writeln('Para Sadhaka yang sungguh-sungguh,');
          writeln('mengendalikan seluruh indrianya dan menjadi');
          writeln('terlelap secara sempurna di dalam diri-Ku,');
          writeln('karena mereka yang pikirannya berada di dalam');
          writeln('pengendaliannya, (maka) kesadaran orang');
          writeln('seperti itu menjadi mantap secara sempurna.');
        end;
    62: begin
          writeln('dhyayato visayan pumsah');
          writeln('sangas tesupajayate');
          writeln('sangat sanjayate kamah');
          writeln('kamat krodho''bhijayate');
          writeln;
          writeln('Orang-orang yang selalu memusatkan pikirannya');
          writeln('pada objek-objek indria, maka keterikatan');
          writeln('pada objek-objek indria itu akan tumbuh. Dari');
          writeln('keterikatan tersebut akan muncul hawa nafsu,');
          writeln('(dan) dari hawa nafsu muncullah kemarahan.');
        end;
    63: begin
          writeln('krodhad bhavati sammohah');
          writeln('sammohat smrti-vibhramah');
          writeln('smrti-bhramsad buddhi-naso');
          writeln('buddhi-nasat pranasyati');
          writeln;
          writeln('Dari kemarahan muncullah kebingungan yang');
          writeln('kuat, akibat kebingungan yang kuat maka');
          writeln('ingatan menjadi kacau. Ketika ingatan menjadi');
          writeln('kacau balau maka kecerdasa menjadi binasa.');
          writeln('Akibat binasanya kecerdasan, maka orang');
          writeln('mengalami kehancuran dirinya.');
        end;
    64: begin
          writeln('raga-dvesa-vimuktais tu');
          writeln('visayan indriyais caran');
          writeln('atma-vasyait vidheyatma');
          writeln('prasadam adhigacchati');
          writeln;
          writeln('Tetapi orang yang mantap di dalam dirinya');
          writeln('menjadi terbebaskan dari rasa suka dan rasa');
          writeln('tidak suka, memiliki kemampuan mengendalikan');
          writeln('indria-indria dengan objek-objek indrianya, maka');
          writeln('ia mencapai kebersihan hati.');
        end;
    65: begin
          writeln('prasade sarva-duhkhanam');
          writeln('hanir asyopajayate');
          writeln('prasanna-cetaso hy asu');
          writeln('buddhih paryavatisthate');
          writeln;
          writeln('Dengan tercapainya kebersihan hati yang');
          writeln('baik, maka segala kedukaannya menjadi');
          writeln('termusnahkan, (dan) orang yang memiliki');
          writeln('kekuasaan seperti itu di dalam dirinya, tanpa');
          writeln('diragukan lagi segera ia memiliki kesadaran yang');
          writeln('mantap sempurna.');
        end;
    66: begin
          writeln('nasti buddhir ayuktasya');
          writeln('na cayuktasya bhavana');
          writeln('na cabhayatah santir');
          writeln('asantasya kutah sukham');
          writeln;
          writeln('Orang yang indria-indrianya tidak terkendalikan');
          writeln('tidak akan memiliki kecerdasa rohani yang');
          writeln('baik, dan orang yang tidak mengendalikan');
          writeln('indria-indrianya tidak akan memiliki kesadaran');
          writeln('spiritual yang baik. Dari ketidakberadaan');
          writeln('kesadaran spiritual yang baik, maka tidak akan');
          writeln('ada kedamaian, akhirnya tanpa kedamaian dari');
          writeln('manakah datangnya kebahagiaan?');
        end;
    67: begin
          writeln('indriyanam hi caratam');
          writeln('yan mano''nuvidhiyate');
          writeln('tad asya harati prajnam');
          writeln('vayur navam ivambhasi');
          writeln;
          writeln('Kecerdasan seseorang dapat dijadikan budak');
          writeln('bahkan oleh satu saja dari indria yang lelap di');
          writeln('dalam objek-objeknya. Ia dapat mengalahkan');
          writeln('kesadaran spiritual orang bagaikan sebuah');
          writeln('perahu yang berada di atas permukaan air');
          writeln('dihempas angin.');
        end;
    68: begin
          writeln('tasmad yasya maha-baho');
          writeln('nigrhitani sarvasah');
          writeln('indriyanindriyarthebhyas');
          writeln('tasya prajna pratisthita');
          writeln;
          writeln('Oleh karena itu, wahai Arjuna yang berlengan');
          writeln('perkasa..., orang yang indria-indrianya terkekang');
          writeln('secara sempurna dari objek-objeknya, maka');
          writeln('orang itu memiliki kecerdasan yang mantap');
          writeln('sempurna.');
        end;
    69: begin
          writeln('ya nisa sarva-bhutanam');
          writeln('tasyam jagarti samyami');
          writeln('yasyam jagrati bhutani');
          writeln('sa nisa pasyato muneh');
          writeln;
          writeln('Malam hari bagi seluruh makhluk hidup adalah');
          writeln('saat terjaga bagi seorang yang sudah mengenda-');
          writeln('alikan indria-indrianya. Saat terjaga bagi seluruh');
          writeln('makhluk hidup adalah malah hari bagi orang');
          writeln('suci yang sudah melihat kebenaran sejati.');
        end;
    70: begin
          writeln('apuryamanam acala-pratistham');
          writeln('samudram apah pravisanti yadvat');
          writeln('tadvat kama yam pravisanti sarve');
          writeln('sa santim apnoti na kama-kami');
          writeln;
          writeln('Sebagaimana air sungai mengalir dari seluruh');
          writeln('arah lalu masuk ke dalam lautan, tetapi air lautan');
          writeln('tetap tenang, seperti itu pula orang yang sudah');
          writeln('mengendalikan indria-indrianya sama sekali');
          writeln('tidak terpengaruh oleh kenikmatan indria-indria.');
          writeln('Hanya orang seperti itulah yang mencapai');
          writeln('kedamaian sejati dan buka orang yang');
          writeln('menginginkan kenikmatan indria-indria.');
        end;
    71: begin
          writeln('vihaya kaman yah sarvan');
          writeln('pumams carati nihsprhah');
          writeln('nirmamo nirahankarah');
          writeln('sa santim adhigacchati');
          writeln;
          writeln('Orang yang sudah meninggalkan segala');
          writeln('jenis keinginan hawa nafsu, hidup bebas dari');
          writeln('keinginan, bebas dari rasa kepemilikan, bebas');
          writeln('dari keakuan palsu, (orang seperti itu) mencapai');
          writeln('kedamaian yang sejati.');
        end;
    72: begin
          writeln('esa brahmi sthitih partha');
          writeln('nainam prapya vimuhyati');
          writeln('sthitvasyam anta-kale''pi');
          writeln('brahma-nirvanam rcchati');
          writeln;
          writeln('Wahai Putra Kunti, inilah tingkat hidup spiritual');
          writeln('sejati. Sesudah orang mencapai tingkat hidup');
          writeln('spiritual seperti ini, orang tidak akan menjadi');
          writeln('terbingungkan. Ketika orang mampu mencapai');
          writeln('tingkat hidup spiritual seperti ini, bahkan pada');
          writeln('saat kematian tiba pun ia dapat mencapai');
          writeln('Brahma Nirvanam, atau tempat tinggal Tuhan');
          writeln('yang kekal abadi.');
        end;
    end;
    readln;
  until (s=0);
end;

Procedure A3;
var s:integer;

begin
  repeat
    clrscr;
    writeln('Pilih Sloka (1 - 43)');
    readln(s);
    case s of
    0: halt;
    1: begin
         writeln('arjuna uvaca');
         writeln('jyayasi cet karmanas te');
         writeln('mata buddhir janardana');
         writeln('tat kim karmani ghore mam');
         writeln('niyojayasi kesava');
         writeln;
         writeln('Arjuna berkata,"Wahai Krsna, jika Anda');
         writeln('berpendapat bahwa kecerdasan lebih baik');
         writeln('daripada pekerjaan, lalu wahai Kesava...,');
         writeln('Mengapa Anda menginginkan hamba menjadi');
         writeln('sibuk dalam perbuatan yang mengerikan ini?');
       end;
    2: begin
         writeln('vyamisreneva vakyena');
         writeln('buddhim mohayasiva me');
         writeln('tad ekam vada niscitya');
         writeln('yena sreyo''ham apnuyam');
         writeln;
         writeln('Kecerdasan hamba dikacaukan oleh kata-kata');
         writeln('Anda yang membingungkan. Beritahukanlah');
         writeln('hamba satu pilihan yang pasti, dengan mana');
         writeln('hamba mendapatkan yang lebih baik untuk diri');
         writeln('hamba.');
    end;
    3: begin
         writeln('sri-bhagavan uvaca');
         writeln('loke''smin dvi-vidha nistha');
         writeln('pura prokta mayanagha');
         writeln('jnana-yogena sankhyanam');
         writeln('karma-yogena yoginam');
         writeln;
         writeln('Sri Bhagavan Krsna bersabda: Wahai Arjuna');
         writeln('yang telah terbebaskan dari dosa-dosa..., di');
         writeln('dunia ini terdapat dua jenis keyakinan. Hal itu');
         writeln('telah Aku jelasakan sebelumnyua kepadamu. Para');
         writeln('ahli Sankhya-yoga menempuhnya melalui jalan');
         writeln('ilmu pengetahuan suci, sedangkan para yogi');
         writeln('menempuhnya melalui jalan perbuatan suci.');
    end;
    4: begin
         writeln('na karmanam anarambhan');
         writeln('naiskarmyam puruso''snute');
         writeln('na ca sannyasanad eva');
         writeln('siddhim samadhigacchati');
         writeln;
         writeln('Sesungguhnya, tidak hanya dengan cara');
         writeln('menghindari melaksanakan pekerjaan orang');
         writeln('dapat mencapai pembebasan dari reaksi');
         writeln('perbuatan, dan tidak hanya dengan melepaskan');
         writeln('ikatan-ikatan duniawi orang dapat dengan');
         writeln('sempurna mencapai keberhasilan.');
    end;
    5: begin
         writeln('na hi kascit ksanam api');
         writeln('jatu tisthaty akarma-krt');
         writeln('karyate hy avasah karma');
         writeln('sarvah prakrti-jai gunaih');
         writeln;
         writeln('Bahkan selama sesaat pun tidak ada orang');
         writeln('dapat hidup di dunia ini tanpa melakukan suatu');
         writeln('perbuatan. Tanpa berdaya semua orang dipaksa');
         writeln('oleh sifat-sifat alam untuk melakukan suatu');
         writeln('perbuatan.');
    end;
    6: begin
         writeln('karmendriyani samyamya');
         writeln('ya aste manasa smaran');
         writeln('indriyarthan vimudhatma');
         writeln('mithyacarah sa ucyate');
         writeln;
         writeln('Orang yang mengendalikan indria-indrianya,');
         writeln('tetapi pikirannya senantiasa mengingat');
         writeln('objek-objek indria, orang seperti itu dikatakan');
         writeln('sebagai orang sangat bodoh yang melakukan');
         writeln('perbuatan berpura-pura.');
    end;
    7: begin
         writeln('yas tv indriyani manasa');
         writeln('niyamyarabhate''rjuna');
         writeln('karmendriyaih karma-yogam');
         writeln('asaktah sa visisyate');
         writeln;
         writeln('Wahai Arjuna, orang yang dengan');
         writeln('sungguh-sungguh berusaha mengendalikan');
         writeln('indria-indrianya dengan pikiran dan dengan');
         writeln('indria-indria pekerjaannya tersebut, dan');
         writeln('tanpa keterikatan apapun mulai melakukan');
         writeln('perbuatan-perbuatan suci di dalam karma-yoga,');
         writeln('maka ia sesungguhnya jauh lebih maju.');
    end;
    8: begin
         writeln('niyatam kuru karma tvam');
         writeln('karma jyayo hy akarmanah');
         writeln('sarira-yatrapi ca te');
         writeln('na prasiddhyed akarmanah');
         writeln;
         writeln('Lakukanlah perbuatan-perbuatan seperti yang');
         writeln('telah ditetapkan di dalam kitab-kitab suci, karena');
         writeln('sesungguhnya adalah lebih baik melakukan');
         writeln('perbuatan daripada tidak berbuat apa-apa.');
         writeln('Bahkan perjalanan badan jasmani ini pun tidak');
         writeln('akan bisa terjadi tanpa melakukan perbuatan.');
    end;
    9: begin
         writeln('yajnarthat karmano''nyatra');
         writeln('loko''yam karma-bandhanah');
         writeln('tad-artham karma kaunteya');
         writeln('muka-sangah samacara');
         writeln;
         writeln('Lakukanlah perbuatan-perbuatan sebagai');
         writeln('persembahan suci kepada Tuhan Yang Maha');
         writeln('Esa. Kalau tidak, perbuatan-perbuatan tersebut');
         writeln('akan mengakibatkan ikatan karma di dunia');
         writeln('ini. Oleh karena itu, wahai Arjuna..., lakukanlah');
         writeln('segala perbuatan sebagai persembahan suci');
         writeln('kepada Tuhan Yang Maha Esa, maka engkau');
         writeln('akan dibebaskan dari segala ikatan karma');
    end;
    10: begin
         writeln('saha-yajnah prajah srstva');
         writeln('purovaca prajapatih');
         writeln('anena prasavisyadhvam');
         writeln('esa vo''stv ista-kama-dhuk');
         writeln;
         writeln('Pada Zaman dahulu kala, Prajapati, sang');
         writeln('Pencipta, telah menciptakan alam semesta');
         writeln('beserta makhluknya melalui persembahan suci');
         writeln('yajna dan bersabda,"Sejahterakanlah semuanya');
         writeln('melalui perbuatan suci ini. Melaksanakan');
         writeln('perbuatan sebagai persembahan suci seperti');
         writeln('ini akan dapat memenuhi segala sesuatu yang');
         writeln('engkau ingingkan');
    end;
    11: begin
         writeln('devan bhavayatanena');
         writeln('te deva bhavayantu vah');
         writeln('parasparam bhavayantah');
         writeln('sreyah param avapsyatha');
         writeln;
         writeln('Puaskanlah para dewa melalui perbuatan-');
         writeln('perbuatan dalam persembahan suci ini, maka');
         writeln('para dewa akan menganugerahkan segala');
         writeln('kesejahteraan kepadamu. Dengan memberikan');
         writeln('kepuasan satu sama lain seperti itu, maka');
         writeln('engkau akan mencapai kemuliaan paling utama.');
    end;
    12: begin
         writeln('istan bhogan hi vo deva');
         writeln('dasyante yajna-bhavitah');
         writeln('tair dattan apradayaibhyo');
         writeln('yo bhunkte stena eva sah');
         writeln;
         writeln('Para dewa yang telah terpuaskan oleh');
         writeln('persembahan-persembahan suci pastilah');
         writeln('senantiasa akan memenuhi keinginan-keinginan');
         writeln('dan memberkahi segala kebutuhan hidup.');
         writeln('Akan tetapi, jika segala berkah tersebut tidak');
         writeln('dipergunakan sebagai persembahan suci, maka');
         writeln('sesungguhnya orang yang menikmati sendirian');
         writeln('berkah-berkah tersebut disebut sebagai seorang');
         writeln('pencuri');
    end;
    13: begin
         writeln('yajna-sistasinah santo');
         writeln('mucyante sarva-kilbisaih');
         writeln('bhunjate te tv agham papa');
         writeln('ye pacanty atma-karanat');
         writeln;
         writeln('Orang saleh yang memakan makanan yang');
         writeln('sudah dipersembahkan terlebih dahulu sebagai');
         writeln('persembahan suci, terbebaskan dari segala');
         writeln('dosa. Sedangkan mereka yang memasak');
         writeln('makanan untuk kenikmatan diri sendiri,');
         writeln('sesungguhnya mereka hanya memakan dosa.');
    end;
    14: begin
         writeln('annad bhavanti bhutani');
         writeln('parjanyad anna-sambhavah');
         writeln('yajnad bhavati parjanyo');
         writeln('yajnah karma-samudbhavah');
         writeln;
         writeln('Semua makhluk hidup dilahirkan dari makanan.');
         writeln('Makanan dilahirkan dari hujan. Dan hujan turun');
         writeln('karena pelaksanaan persembahan-persembahan');
         writeln('suci yajna. Selanjutnya, persembahan suci yajna');
         writeln('terlahir dari perbuatan.');
    end;
    15: begin
         writeln('karma brahmodbhavam viddhi');
         writeln('brahmaksara-samudbhavam');
         writeln('tasmat sarva-gatam brahma');
         writeln('nityam yajne pratisthitam');
         writeln;
         writeln('Ketahuilah bahwa perbuatan muncul dari Veda,');
         writeln('dan Veda muncul dari Aksara Brahma, Tuhan');
         writeln('Yang Maha Esa. Oleh karena itu, Tuhan Yang');
         writeln('Maha Esa senantiasa berada pada persembahan');
         writeln('suci yajna.');
    end;
    16: begin
         writeln('evam pravartitam cakram');
         writeln('nanuvartayatiha yah');
         writeln('aghayur indriyaramo');
         writeln('mogham partha sa jivati');
         writeln;
         writeln('Arjuna yang baik hati,orang yang tidak');
         writeln('melaksanakan korban suci tersebut seperti yang');
         writeln('telah ditetapkan di dalam Veda, pasti hidupnya');
         writeln('penuh dengan dosa. Sia-sialah kehidupan');
         writeln('orang seperti itu, dimana hidupnya hanya untuk');
         writeln('memuaskan indria-indrianya.');
    end;
    17: begin
         writeln('yas tv atma-ratir eva syad');
         writeln('atma-trptas ca manavah');
         writeln('atmany eva ca santustas');
         writeln('tasya karyam na vidyate');
         writeln;
         writeln('Akan tetapi, orang yang menikmati di dalam');
         writeln('Sang Diri, orang yang puas hati di dalam dirinya,');
         writeln('dan berbahagia sepenuhnya hanya di dalam');
         writeln('Sang Diri Sejatinya, maka bagi orang seperti itu');
         writeln('tidak ada tugas kewajiban apapun lagi.');
    end;
    18: begin
         writeln('naiva tasya krtenartho');
         writeln('nakrteneha kascana');
         writeln('na casya sarva-bhutesu');
         writeln('kascid artha-vyapasyaha');
         writeln;
         writeln('Bagi orang yang sudah mencapai tingkat');
         writeln('keinsafan diri seperti itu, di dunia ini ia tidak');
         writeln('mempunyai tujuan apapun dari pelaksanaan tu-');
         writeln('gas kewajiban, dan juga tidak mempunyai tujuan');
         writeln('apapun dengan tidak melaksanakan tugas ke-');
         writeln('wajiban. Dan dalam hubungan dengan makhluk');
         writeln('hidup manapun ia sama sekali tidak mempunyai');
         writeln('pamrih tujuan dalam bentuk apa pun.');
    end;
    19: begin
          writeln('tasmad asaktah satatam');
          writeln('karyam karma samacara');
          writeln('asakto hy acaran karma');
          writeln('param apnoti purusah');
          writeln;
          writeln('Oleh karena itu, lakukanlah tugas kewajiban');
          writeln('tanpa keterikatan pada tujuan dari perbuatan,');
          writeln('karena orang yang melakukan tugas');
          writeln('kewajibannya tanpa keterikatan pada tujuan,');
          writeln('maka orang seperti itu akan sampai kepada');
          writeln('Tuhan Yang Maha Esa.');
    end;
    20: begin
          writeln('karmanaiva hi samsiddhim');
          writeln('asthita janakadayah');
          writeln('loka-sangraham evapi');
          writeln('sampasyan kartum arhasi');
          writeln;
          writeln('Raja suci bernama Janaka dan yang lain-lain');
          writeln('telah mencapai kesempurnaan hanya dengan');
          writeln('melaksanakan tugas-tugas kewajiban suci.');
          writeln('Oleh karena itu, demi kepentingan mendidik');
          writeln('masyarakat biasa, engkau hendaknya melakukan');
          writeln('tugas kewajiban tanpa keterikatan pada tujuan.');
    end;
    21: begin
          writeln('yad yad acarati sresthas');
          writeln('tad tad evetaro janah');
          writeln('sa yat pramanan kurute');
          writeln('lokas tad anuvartate');
          writeln;
          writeln('Apa-apa saja yang dilakukan oleh pemimpin');
          writeln('masyarakat, maka masyarakat biasa akan');
          writeln('mengikutinya. Aturan-aturan apa saja yang');
          writeln('ditetapkan oleh pemimpin tersebut, maka');
          writeln('masyarakat akan mengikutinya denga patuh.');
    end;
    22: begin
          writeln('na me parthasti kartavyam');
          writeln('trisu lokesu kincana');
          writeln('nanavaptam avaptavyam');
          writeln('varta eva ca karmani');
          writeln;
          writeln('Wahai Arjuna, di alam Triloka ini tidak ada tugas');
          writeln('kewajiban apa pun yang harus Ku-lakukan,');
          writeln('dan tidak ada suatu apa pun yang tidak dapat');
          writeln('dicapai oleh-Ku. Tetapi, Aku tetap melakukan');
          writeln('tugas kewajiban-Ku dengan baik.');
    end;
    23: begin
          writeln('yadi hy aham na varteyam');
          writeln('jatu karmany atandritah');
          writeln('mama vartmanuvartante');
          writeln('manusyah partha sarvasah');
          writeln;
          writeln('Wahai Arjuna, apabila karena (atas pertimban-');
          writeln('gan) keberhati-hatian lalu Aku tidak melakukan');
          writeln('tugas kewajiban-Ku (maka segala sesuatu akan');
          writeln('menjadi kacau), sebab orang-orang mengikuti');
          writeln('jalan-Ku dalam segala hal.');
    end;
    24: begin
          writeln('utsideyur ime loka');
          writeln('na kuryam karma ced aham');
          writeln('sankarasya ca karta syam');
          writeln('upahanyam imah prajah');
          writeln;
          writeln('Jika Aku tidak melakukan tugas kewajiban-Ku,');
          writeln('maka seluruh dunia ini akan menjadi kacau');
          writeln('balau. Dengan demikian, Aku akan menjadi');
          writeln('penyebab munculnya orang-orang yang tidak');
          writeln('diinginkan di masyarakat, dan Aku akan menjadi');
          writeln('penyebab kehancuran dari kelanjutan hidup');
          writeln('manusia (di muka bumi ini).');
    end;
    25: begin
          writeln('saktah karmany avidvamso');
          writeln('yatha kurvanti bharata');
          writeln('kuryad vidvams tathasaktas');
          writeln('cikirsur loka-sangraham');
          writeln;
          writeln('Sebagaimana orang-orang yang tidak terpelajar');
          writeln('melaksanakan tugas kewajibannya karena');
          writeln('keterikatan pada hasil, seperti itu pula orang-');
          writeln('orang terpelajar yang mengetahui kebenaran');
          writeln('hendaknya melakukan tugas kewajibannya tanpa');
          writeln('keterikatan demi kesejahteraan umat manusia.');
    end;
    26: begin
          writeln('na budddhi-bhedam janayed');
          writeln('ajnanam karma-sanginam');
          writeln('josayet sarva-karmani');
          writeln('vidvan yuktah samacaran');
          writeln;
          writeln('Orang-orang bijaksana hendaknya tidak menga-');
          writeln('caukan pemikiran orang-orang yang berada');
          writeln('dalam kebodohan yang sangat terikat pada');
          writeln('pahala-pahala dari perbuatan-perbuatan yang');
          writeln('dilakukan. Orang-orang bijaksana hendaknya');
          writeln('melaksanakan tugas kewajiban dengan baik, dan');
          writeln('mengajak mereka untuk melaksanakan tugas');
          writeln('kewajiban dengan baik.');
    end;
    27: begin
          writeln('prakrteh kriyamanani');
          writeln('gunaih karmani sarvasah');
          writeln('ahankara-vimudhatma');
          writeln('kartaham iti manyate');
          writeln;
          writeln('Dalam segala hal sesungguhnya segala jenis');
          writeln('perbuatan ditentukan oleh sifat-sifat alam.');
          writeln('Tetapi, orang-orang yang dibingungkan oleh');
          writeln('keakuan palsu berpendapat,"Akulah yang');
          writeln('melakukan semua ini." Demikian ia beranggapan.');
    end;
    28: begin
          writeln('tattva-vit tu maha-baho');
          writeln('guna-karma-vibhagayoh');
          writeln('guna gunesu vartanta');
          writeln('iti matva na sajjate');
          writeln;
          writeln('Akan tetapi, wahai Arjuna yang berlengan');
          writeln('perkasa, orang-orang bijaksana yang telah');
          writeln('mengetahui kebenaran yang sejati bertindak');
          writeln('di dalam sifat-sifat yang sempurna setelah');
          writeln('mempertimbangkan dengan baik antara');
          writeln('sifat-sifat dan pekerjaan-pekerjaan. Dengan');
          writeln('berpendapat demikian, mereka menjadi tidak');
          writeln('terikat pada tujuan dari perbuatan-perbuatannya.');
    end;
    29: begin
          writeln('prakrter guna-sammudhah');
          writeln('sajjante guna-karmasu');
          writeln('tan akrtsna-vido mandan');
          writeln('krtsna-vin na vicalayte');
          writeln;
          writeln('Orang-orang bodoh yang dibingungkan oleh');
          writeln('sifat-sifat alam menjadi terikat pada sifat-sifat');
          writeln('alam dan perbuatan-perbuatan. Orang-orang');
          writeln('yang berpengetahuan sempurna hendaknya jan-');
          writeln('gan membingungkan mereka yang sepenuhnya');
          writeln('berada di dalam kebodohan disebabkan oleh');
          writeln('kecerdasan spiritualnya tidak berkembang.');
    end;
    30: begin
          writeln('mayi sarvani karmani');
          writeln('sannyasyadhyatma-cetasa');
          writeln('nirasir nirmamo bhutva');
          writeln('yudhyasva vigata-jvarah');
          writeln;
          writeln('Wahai Arjuna, dengan didasarkan pada');
          writeln('kecerdasan spiritual, persembahkanlah');
          writeln('kepada-Ku segala tugas kewajiban yang engkau');
          writeln('lakukan, tanpa harapan-harapan apa pun, tanpa');
          writeln('rasa kepemilikan, tanpa rasa penyesalan sedikit');
          writeln('pun, dan setelah itu bertempurlah.');
    end;
    31: begin
          writeln('ye me matam idam nityam');
          writeln('anutisthanti manavah');
          writeln('sraddhavanto ''nasuyanto');
          writeln('mucyante te''pi karmabhih');
          writeln;
          writeln('Orang-orang yang sudah dibebaskan dari rasa iri');
          writeln('hati dan dengan penuh rasa bhakti senantiasa');
          writeln('melakukan tugas-tugas kewajibannya sesuai');
          writeln('dengan perintah-perintah-Ku, mereka pun akan');
          writeln('terbebaskan dari ikatan-ikatan karma.');
    end;
    32: begin
          writeln('ye tv etad abhyasuyanto');
          writeln('nanutisthanti me matam');
          writeln('sarva-jnana-vimudhams tan');
          writeln('viddhi nastan acetasah');
          writeln;
          writeln('Akan tetapi, mereka yang disebabkan oleh');
          writeln('rasa iri hati terhadap ajaran-ajaran-Ku ini, maka');
          writeln('mereka tidak melaksanakannya. Orang-orang');
          writeln('bodoh seperti itu tidak memiliki kecerdasan');
          writeln('spiritual menjadi kehilangan segala jenis');
          writeln('pengetahuan, dan mereka akan menemukan');
          writeln('kehancuran dengan sendirinya.');
    end;
    33: begin
          writeln('sadrsam cestate svasyah');
          writeln('prakrter jnanavan api');
          writeln('prakrtim yanti bhutani');
          writeln('nigrahah kim karisyati');
          writeln;
          writeln('Seluruh makhluk hidup bertindak sesuai dengan');
          writeln('alamnya masing-masing. Orang bijaksana pun');
          writeln('bertindak sesuai dengan sifat alamnya sendiri.');
          writeln('Lalu dalam hal ini apa yang orang akan lakukan');
          writeln('dengan pengekangan?');
    end;
    34: begin
          writeln('indriyasyendriyasyarthe');
          writeln('raga-dvesau vyavasthitau');
          writeln('tayor na vasam agacchet');
          writeln('tau hy asya paripanthinau');
          writeln;
          writeln('Pengaturan sifat keterikatan dan kebencian');
          writeln('di dalam diri orang ditentukan oleh');
          writeln('sentuhan-sentuhan indria dengan objek-objek');
          writeln('indria. Orang hendaknya tidak dikendalikan oleh');
          writeln('kedua sifat tersebut karena ia merupakan musuh');
          writeln('penghalang di dalam jalan keinsafan diri.');
    end;
    35: begin
          writeln('sreyan sva-dharmo vigunah');
          writeln('para-dharmmat sv-anusthitah');
          writeln('sva-dharme nidhanam sreyah');
          writeln('para-dharmo bhayavahah');
          writeln;
          writeln('Sesungguhnya jauh lebih baik melaksanakan');
          writeln('tugas-tugas kewajiban sendiri walaupun dilak-');
          writeln('ukan dengan penuh kekurangan dibandingkan');
          writeln('dengan melaksanakan tugas kewajiban orang');
          writeln('lain walaupun dilakukan dengan sempurna.');
          writeln('Ketika orang menekuni tugas kewajibannya');
          writeln('sendiri, kematian pun menjadi berkah, sebab');
          writeln('melaksanakan tugas kewajiban orang lain itu');
          writeln('penuh dengan bahaya.');
    end;
    36: begin
          writeln('arjuna uvaca');
          writeln('atha kena prayukto''yam');
          writeln('papam carati purusah');
          writeln('aniccham api varsneya');
          writeln('balad iva niyojitah');
          writeln('Arjuna berkata: Dalam hal ini, apakah sebenarnya');
          writeln('yang mendorong orang untuk berbuat dosa?');
          writeln('Wahai Sri Krsna..., bahkan tanpa diinginkan pun');
          writeln('seolah-olah dipaksa oleh kekuatan hebat untuk');
          writeln('berbuat demikian');
    end;
    37: begin
          writeln('sri-bhagavan uvaca');
          writeln('kama esa krodha esa');
          writeln('rajo-guna-samudbhavah');
          writeln('mahasano maha-papma');
          writeln('viddhy enam iha vairinam');
          writeln;
          writeln('Sri Krsna bersabda: Adalah nafsu keinginan,');
          writeln('adalah kemarahan yang muncul dari sifat ken-');
          writeln('afsuan, ia sangat berdosa dan memakan habis');
          writeln('segalanya. Wahai Arjuna, ketahuilah bahwa ia');
          writeln('adalah musuh berbahaya di dunia material ini.');
    end;
    38: begin
          writeln('dhumenavriyate vahnir');
          writeln('yathadarso malena ca');
          writeln('yatholbenavrto garbhas');
          writeln('tatha tenedam avrtam');
          writeln;
          writeln('Sebagaimana halnya api ditutupi oleh asap,');
          writeln('dan cermin ditutupi oleh debu, atau janin');
          writeln('ditutupi oleh kandungan, seperti itu pula halnya');
          writeln('kesadaran spiritual seseorang ditutupi oleh hawa');
          writeln('nafsu ini.');
    end;
    39: begin
          writeln('avrtam jnanam etena');
          writeln('jnanino nitya-vairina');
          writeln('kama-rupena kaunteya');
          writeln('duspurenanalena ca');
          writeln;
          writeln('Wahai Arjuna, hawa nafsu ini dengan begitu kuat');
          writeln('menutupi pengetahuan suci seseorang. Dan,');
          writeln('bagi orang-orang bijaksana, ia adalah musuh');
          writeln('abadi dalam bentuk hawa nafsu. Ia membakar');
          writeln('segalanya bagaikan api menyala-nyala dan tidak');
          writeln('pernah terpuaskan.');
    end;
    40: begin
          writeln('indriyani mano buddhir');
          writeln('asyadhisthanam ucyate');
          writeln('etair vimohayaty esa');
          writeln('jnanam avrtya dehinam');
          writeln;
          writeln('Indria-india, pikiran dan kecerdasan dikatakan');
          writeln('sebagai tempat duduk yang nyaman bagi');
          writeln('hawa nafsu ini. melalui indria-indria, pikiran');
          writeln('dan kecerdasan, hawa nafsu ini menutupi');
          writeln('pengetahuan suci dan membingungkan Sang');
          writeln('Roh yang berada di dalam badan jasmani.');
    end;
    41: begin
          writeln('tasmat tvam indriyany adau');
          writeln('niyamya bharatarsabha');
          writeln('papmanam prajahi hy enam');
          writeln('jnana-vijnana-nasanam');
          writeln;
          writeln('Oleh karena itu, wahai Arjuna yang paling utama');
          writeln('di anatara keturunan Bharata, sedari awal engkau');
          writeln('hendaknya mengendalikan indria-indria tersebut.');
          writeln('Dengan kekuatan sepenuhnya bunuhlah hawa');
          writeln('nafsu ini yang merupakan penghancur segala');
          writeln('pengetahuan dan keinsafan diri.');
    end;
    42: begin
          writeln('indriyani parany ahur');
          writeln('indriyebhyah param manah');
          writeln('manasas tu para buddhir');
          writeln('yo buddheh paratas tu sah');
          writeln;
          writeln('Disebutkan bahwa indria-indria bersifat lebih');
          writeln('halus (lebih kuat) daripada alam prakrti, lebih');
          writeln('kuat daripada indria-indria adalah pikiran, lebih');
          writeln('kuat daripada pikiran adalah kecerdasan, dan');
          writeln('lebih kuat daripada kecerdasan adalah dia, sang');
          writeln('hawa nafsu.');
    end;
    43: begin
          writeln('evam buddheh param buddhva');
          writeln('samstabhyatmanam atmana');
          writeln('jahi satrum maha-baho');
          writeln('kama-rupam durasadam');
          writeln;
          writeln('Mengetahui bahwa hawa nafsu lebih kuat');
          writeln('daripada kecerdasan, maka setelah menguasai');
          writeln('diri melalui Sang Diri, wahai Arjuna yang');
          writeln('berlengan perkasa, bunuhlah musuh yang tidak');
          writeln('terkalahkan dalam bentuk hawa nafsu.');
        end;
    end;
    readln;
  until (s=0);
end;

begin
  cover;
  readkey;
  clrscr;
  bab;
  readln(a);
  case a of
  1:a1;
  2:a2;
  3:a3;
  end;
  readln;
  end.
